### ISSUE TITLE
[QUESTION]: I'm recreating your mod for 1.16.4

### ISSUE THREAD

**Issue by Daniel-Mendes** [The-Fireplace-Minecraft-Mods/Simply-Caterpillar#3]
Hello,

I'liked your mod and i say that it was not updated for a while.

So I say, i'm a developer I could try to port your mod (my first experience in modding), I'm following a [tutorial](https://www.youtube.com/playlist?list=PLDhiRTZ_vnoUI3-9z0Zg-I8tTSp3EfOia) right now.

I just want to know if one day that I finish the version for 1.16.4 can I create a Pull request so you update the mod on curseforge for everyone that want to use the mod ?

PS. I don't know if I will be able to finish it, but just want to know if I have to publish the mod my own.

**Comment by The-Fireplace** [comment]
Yes
